<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WebForm1.aspx.cs" Inherits="Upi.WebForm1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
        <asp:GridView ID="grdViewEstudiante" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" OnRowDeleting="grdViewEstudiante_RowDeleting" OnRowEditing="grdViewEstudiante_RowEditing" OnRowUpdating="grdViewEstudiante_RowUpdating" OnSelectedIndexChanged="grdViewEstudiante_SelectedIndexChanged">
        </asp:GridView>
        <br />
        CODIGO:&nbsp; <asp:TextBox ID="txtCodigoEstudiante" runat="server" CausesValidation="True"></asp:TextBox>
        <br />
        <br />
        NOMBRE:
        <asp:TextBox ID="txtNombreEstudiante" runat="server"></asp:TextBox>
        <br />
        <br />
        <asp:Button ID="btnIngresarEstudiante" runat="server" OnClick="btnIngresarEstudiante_Click" Text="Ingresar" />
        <br />
        <br />
        <asp:Label ID="lblEstadoInsertar" runat="server"></asp:Label>
    
    </div>
    </form>
</body>
</html>
